version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - /mnt/user/appdata/beets-audible:/config
      - ./plugins:/plugins
      - ./scripts:/config/custom-cont-init.d
      - /mnt/user/AudYard/audiobooks/:/audiobooks
      - /mnt/user/AudYard/temp/untagged:/untagged
    restart: unless-stopped
